### ISSUE TITLE
无法在iOS设备上使用矢量绘图绘制圆形

### ISSUE THREAD

**Issue by Danielhu229** [egret-labs/egret-ios-support#3]
Xcode 版本：7.1.1
iOS 版本：9.1
设备：ipad mini2

界面中有多处需要绘制圆形，在chrome上均能正确绘制但无法在iOS设备上绘制
截取某段代码如下

    this.graphics.beginFill(0x00ccff, 1);
    this.graphics.drawCircle(this.physicsBody.position[0], this.physicsBody.position[1], 30);
    this.graphics.endFill();

除了圆形以外，线条可以正确绘制，其他的尚未测试

其他信息：
* 绘制的线条数量大约有100条，长度很短
* 原本需要绘制的圆形数量大约有20个，大小100像素

**Comment by h-wei** [comment]
我们正在验证和处理这个问题

**Comment by h-wei** [comment]
@Danielhu229 ，请问你是在iOS support的哪一个版本上面出现的，我们对最近的两个版本（v2.5.6和v2.5.5)按照你的方法进行了测试，但是没有重现。

**Comment by Danielhu229** [comment]
2.5.6版本，另外 egret-core 的版本也是2.5.6，
我另外测试了一下，新建一个项目，只改动了Main中的createGameSence 函数如下
        var shape: egret.Shape = new egret.Shape();
        this.addChild(shape);
        shape.graphics.beginFill(0x00ffff, 1);
        shape.graphics.drawCircle(300, 300, 30);
        shape.graphics.endFill();

        shape.graphics.beginFill(0x00ffff, 1);
        shape.graphics.drawRect(10, 10, 100, 100);
        shape.graphics.endFill();

依旧无法在iOS上绘制圆形，在chrome上绘制正确
我是否遗漏了什么步骤？

**Comment by h-wei** [comment]
@Danielhu229 我们已经确认问题，正在尝试修复，谢谢。

**Comment by h-wei** [comment]
@Danielhu229 这个问题我们已经修复了，将在2.5.7中发布，也就是本周五
