### ISSUE TITLE
请问自定义热更有真机测试吗？

### ISSUE THREAD

**Issue by helojo** [egret-labs/egret-ios-support#5]
写代码能不能负点责任？

**Comment by WanderWang** [comment]
您好~！我们在 3.2.6 版本引入新功能的时候，由于我们的疏忽，导致了创建 iOS-app 创建项目后因为向下兼容出现了问题而导致运行失败。
这个问题目前已经得到解决，我们接下来会进一步在提供更多功能的同时稳定代码质量以及做好向下兼容工作。
感谢开发者对我们的批评和鞭策
